#!/usr/bin/env python3
# emit_config.py — tiered config.h emitter from mined values
# Usage: python emit_config.py <values.json> <out_config.h>
# Values JSON: {"NAME": {"value": "0x..", "tier": "DISASM|DUMP|CALIB|STD"}}
import json
import sys

HEADER = """// config.h — AUTOGENERATED by project/tools (season_update.py)
// Provenance tiers: [DISASM] disasm / [DUMP] dump.cs / [CALIB] runtime dual
// hypothesis / [STD] universal + guards. No number without a tier.
#ifndef CONFIG_H
#define CONFIG_H

#include <stdint.h>
"""

FOOTER = """
#endif
"""


def main():
    if len(sys.argv) != 3:
        print('usage: emit_config.py <values.json> <out_config.h>')
        return 1
    vals = json.load(open(sys.argv[1], encoding='utf-8'))
    lines = [HEADER]
    for name in sorted(vals):
        v = vals[name]
        lines.append('#define %-22s %s   // [%s]' % (name, v['value'], v['tier']))
    lines.append(FOOTER)
    open(sys.argv[2], 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
    print('wrote %s (%d defines)' % (sys.argv[2], len(vals)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
